# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf51a1b4cd86ca0bf0a3928eb4e366c44bafe2f5fe4cea965cda70d51b7d7a0668516b78cdb65af7fe430b9765323756000efe87a759e2a7c3f469516e2cbea

test:
  secret_key_base: f406050765653e8402d1de1e1b699099f4b6da2bd13a61b94915d70027aedebbe3aecaaacdbb923c25aad10b035a822d1ac32a567808d9cd89f98feb3d9bcc14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
